trigger:
- main
- Release_*
- development



jobs:
# - job: JSWrapper
#   timeoutInMinutes: 60
#   pool:
#     vmImage: ubuntu-20.04
#   steps:
#   - task: CmdLine@2
#     displayName: get dockerfile
#     inputs:
#       script: 'wget https://raw.githubusercontent.com/rdkit/rdkit/master/Code/MinimalLib/docker/Dockerfile'
#   - task: Docker@2
#     displayName: build js wrappers
#     inputs:
#       command: build
- job: linux_cffi
  timeoutInMinutes: 60
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: linux_cffi_build.yml
- job: mac_cffi
  timeoutInMinutes: 60
  pool:
    vmImage: macos-10.15
  steps:
  - template: mac_cffi_build.yml
